// actionTypes.js
export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const DELETE_TODO = 'DELETE_TODO';

export const ADD_DISCUSSION = 'ADD_DISCUSSION';
export const FETCH_DISCUSSIONS_REQUEST = 'FETCH_DISCUSSIONS_REQUEST';
export const FETCH_DISCUSSIONS_ERROR = 'FETCH_DISCUSSIONS_ERROR';
export const FETCH_DISCUSSIONS_SUCCESS = 'FETCH_DISCUSSIONS_SUCCESS';
